### ISSUE TITLE
ReportCard.js causes a crash if result object is undefined 

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-grasp#10]
Putting this here so I remember to fix it later. 

I think we're not doing error checking correctly in ReportCard.js. 

/Users/abrahamq/Documents/urop/cognicity-grasp/ReportCard.js:157
          else if (result[0].received === false){
                            ^

TypeError: Cannot read property 'received' of undefined
    at /Users/abrahamq/Documents/urop/cognicity-grasp/ReportCard.js:157:29
    at null.<anonymous> (/Users/abrahamq/Documents/urop/cognicity-grasp/ReportCard.js:85:6)
    at Query.handleReadyForQuery (/Users/abrahamq/Documents/urop/cognicity-grasp/node_modules/pg/lib/query.js:114:10)
    at null.<anonymous> (/Users/abrahamq/Documents/urop/cognicity-grasp/node_modules/pg/lib/client.js:172:19)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/abrahamq/Documents/urop/cognicity-grasp/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)

**Comment by MaanasaPriyaa** [comment]
There is an issue assigned to me that discusses about error handling. I guess this will come under that issue. Can you check? I'm planning to work on this today.

**Comment by talltom** [comment]
I refactored a lot of the ReportCard.js code yesterday to help make it more testable.

The above error should have been fixed in: https://github.com/urbanriskmap/cognicity-grasp/commit/691a2031452f009466c1d86cb80a373220997cf7

**Comment by abrahamq** [comment]
Hey, sorry didn't see that, maybe we should merge master into mvp-cards?

**Comment by talltom** [comment]
Yes - probably good to do this incrementally. I've finished updating with the ReportCard.js logic for the time being, but now working on Bot.js.

**Comment by talltom** [comment]
Hi @abrahamq - now you've pulled latest master to MVP can we close this?

**Comment by abrahamq** [comment]
I think so, let me make sure tonight and I'll close it.
